import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import ConditionalLayout from "../components/conditionallayout";
import { UserProvider } from "../Context/userContext";

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Shine Bright!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/gem.png" />
      </head>
      <body className={`${jost.variable} ${jost.variable} antialiased`}>
        <UserProvider>
          <ConditionalLayout>{children}</ConditionalLayout>
        </UserProvider>
      </body>
    </html>
  );
}
